# Generated by Django 4.1.1 on 2022-09-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.CharField(blank=True, choices=[(None, '--'), ('1', '10代'), ('2', '20代'), ('3', '30代'), ('4', '40代'), ('5', '50代')], default=None, max_length=1, null=True, verbose_name='年代'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, choices=[(None, '--'), ('0', '男性'), ('1', '女性')], default=None, max_length=1, null=True, verbose_name='性別'),
        ),
    ]
