# Generated by Django 4.0.6 on 2022-07-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikamika', '0002_remove_mikamika_text_remove_mikamika_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikamika',
            name='hyouka',
            field=models.CharField(blank=True, choices=[('0', 'soso'), ('1', 'good')], max_length=10, null=True, verbose_name='評価'),
        ),
    ]
