# Generated by Django 4.0.6 on 2022-09-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikamika', '0009_mikamika_views_alter_mikamika_todou'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikamika',
            name='image',
            field=models.ImageField(default=2, upload_to='img/'),
            preserve_default=False,
        ),
    ]
