# Generated by Django 4.2 on 2023-04-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikamika', '0010_mikamika_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikamika',
            name='review',
            field=models.CharField(default='', max_length=200, verbose_name='レビュー'),
        ),
        migrations.AddField(
            model_name='mikamika',
            name='userstore',
            field=models.CharField(default='', max_length=40, verbose_name='ユーザー店名'),
        ),
        migrations.AddField(
            model_name='mikamika',
            name='usersubject',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='タイトル'),
        ),
    ]
