# Generated by Django 4.2 on 2023-04-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikamika', '0011_mikamika_review_mikamika_userstore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userstore', models.CharField(default='', max_length=40, verbose_name='ユーザー店名')),
                ('usersubject', models.CharField(blank=True, max_length=20, null=True, verbose_name='タイトル')),
                ('review', models.CharField(default='', max_length=200, verbose_name='レビュー')),
            ],
        ),
        migrations.RemoveField(
            model_name='mikamika',
            name='review',
        ),
        migrations.RemoveField(
            model_name='mikamika',
            name='userstore',
        ),
        migrations.RemoveField(
            model_name='mikamika',
            name='usersubject',
        ),
    ]
