# Generated by Django 4.2 on 2023-04-14 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mikamika', '0012_userinfo_remove_mikamika_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='create_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='todou',
            field=models.CharField(blank=True, choices=[('0', 'tokyo'), ('1', 'oosaka'), ('2', 'kyouto')], max_length=10, null=True, verbose_name='都道府県'),
        ),
    ]
