# Generated by Django 4.2 on 2023-04-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikamika', '0014_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userstore',
            field=models.CharField(default='', max_length=40, unique=True, verbose_name='ユーザー店名'),
        ),
    ]
