# Generated by Django 4.2 on 2023-04-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mikamika', '0015_alter_userinfo_userstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mikamika.userinfo', to_field='userstore', verbose_name='対象店名'),
        ),
    ]
