# Generated by Django 4.0.6 on 2022-07-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikamika', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mikamika',
            name='text',
        ),
        migrations.RemoveField(
            model_name='mikamika',
            name='title',
        ),
        migrations.AddField(
            model_name='mikamika',
            name='bikou',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='一言'),
        ),
        migrations.AddField(
            model_name='mikamika',
            name='hyouka',
            field=models.CharField(blank=True, choices=[('0', 'soso'), ('1', 'good')], max_length=10, null=True, verbose_name='評価して下さい'),
        ),
        migrations.AddField(
            model_name='mikamika',
            name='store',
            field=models.CharField(default='', max_length=40, verbose_name='店名'),
        ),
    ]
