# Generated by Django 4.0.6 on 2022-07-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikamika', '0003_alter_mikamika_hyouka'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikamika',
            name='todou',
            field=models.CharField(blank=True, choices=[('0', 'tokyo'), ('1', 'oosaka')], max_length=10, null=True, verbose_name='都道府県'),
        ),
    ]
