# Generated by Django 4.0.6 on 2022-07-28 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mikamika', '0007_mikamika_create_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikamika',
            name='create_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
